### ISSUE TITLE
Remover comentários desnecessários

### ISSUE THREAD

**Issue by Ronkiro** [WalterSilva5/gestao-de-lan-house#1]
O repo contém comentários irrelevantes, marcando apenas o escopo de funções do Python.

Isto deveria ser algo que um dev Python já sabe, não tendo portanto a necessidade destes.

**Comment by WalterSilva5** [comment]
vlw amigo, eu estava bem noob em programação quando fiz esse projeto e foi apenas para uso pessoal, obrigado aviso, tmj!
