### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Ronkiro** [WalterSilva5/gestao-de-lan-house#2]
O repo não é facilmente reproduzível devido a falta de um arquivo requirements.txt

Dica: Dá para se montar um facilmente usando o comando `pip freeze` na sua env, pode redirecionar o pipe para um arquivo com `pip freeze > requirements.txt`

**Comment by WalterSilva5** [comment]
kkkk, como te falei eu não entendia de nada quando fiz o projeto, vlw!
